((game "Super Monkey Ball 2: Monkeyed Ball")
 (category "Story Mode All Levels") (split_names Green Apricot Blue)
 (personal_best (attempt 3000)
  (splits ((title Green) (time 3000) (is_gold false))
   ((title Apricot) (time 5000) (is_gold false))
   ((title Blue) (time 5000) (is_gold false))))
 (golds ((title Green) (duration 2000)) ((title Apricot) (duration 2000))
  ((title Blue) (duration 2000)))
 (history
  ((attempt 2500) ((title Green) (time 3000) (is_gold false))
   ((title Green) (time 3000) (is_gold false))
   ((title Green) (time 3000) (is_gold false)))
  ((attempt 2500) ((title Green) (time 3000) (is_gold false))
   ((title Green) (time 3000) (is_gold false))
   ((title Green) (time 3000) (is_gold false)))))
